title = "mosiman"

baseURL = "http://mosiman.ca"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Dillon Chan's personal website"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/mosiman"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/static/images/darkbike.jpeg"
  recent_posts_number = 2

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
