title = "mosiman"

baseURL = "http://mosiman.ca"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-156032479-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Dillon Chan's personal website"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/mosiman"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/static/images/darkbike.jpeg"
  recent_posts_number = 2
  # If mainSections not defined, it is automatically mainSections = [VAR] where VAR is the section with the most posts.
  mainSections = ["projects", "posts"]

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "Resume"
    identifier = "resume"
    url = "/files/webresume_dillonchan.pdf"

[markup.goldmark.renderer]
  unsafe = true


# Projects photo credits:
# Photo by Jo Szczepanska on Unsplash
# Posts photo credits:
# Photo by Kelly Sikkema on Unsplash
