name: Build Hugo container
on: [push]
jobs:
  build_x86_64:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Running builds for x86_64"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "DOCKER USERNAME: $DOCKER_USERNAME"
          docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
          ./docker-build.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
  build_aarch64:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    steps:
      - run: echo "🎉 Running builds for x86_64"
      - name: Check out repo
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Run on arch action
        uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          env: |
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            ls
            echo "DOCKER USERNAME: $DOCKER_USERNAME"
            docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
            uname -a
            ./docker-build.sh

